# Configuration
MULTICAST_ADDRESS   = "239.168.168.168"
MULTICAST_PORT      = 5000
MULTICAST_TTL       = 4
MULTICAST_COUNT     = 10
MULTICAST_SEND_RATE = 1
MULTICAST_PAYLOAD   = "It is not the network"

